x-restart-policy: &restart_policy
    restart: unless-stopped

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: order-placement-app
        <<: *restart_policy
        working_dir: /var/www
        volumes:
            - ./:/var/www
        depends_on:
            - db
            - redis

    nginx:
        image: nginx:latest
        container_name: order-placement-nginx
        <<: *restart_policy
        ports:
            - '80:80'
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d
        depends_on:
            -   app

    db:
        image: mysql:8.0
        container_name: order-placement-db
        <<: *restart_policy
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - dbdata:/var/lib/mysql

    redis:
        image: redis:alpine
        container_name: order-placement-redis
        <<: *restart_policy
        ports:
            - '6379:6379'

    queue:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: order-placement-queue
        <<: *restart_policy
        working_dir: /var/www
        command: php artisan horizon
        volumes:
            -   ./:/var/www
        depends_on:
            - app
            - redis

volumes:
    dbdata:
